/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import com.ConvertAlatToObject;
import com.ConvertUserToObject;
import com.ConvertJenisToObject;
import com.ConvertPembayaranToObject;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import com.Alat;
import com.Jenis;
import com.User;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.PrintJob;

/**
 *
 * @author MuhammadRauf
 */
public class MainFormadmin extends javax.swing.JFrame {

    /**
     * Creates new form MainFomadmin
     */
    public MainFormadmin() {
        initComponents();
        setDataUser();
        setDataAlat();
        setDataPembayaran();
        setDataRawat();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnRawat = new javax.swing.JButton();
        btnAlat = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlUtama = new javax.swing.JPanel();
        pnlrawat = new javax.swing.JPanel();
        pnlInputRawat = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtid_rawat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtjenisrawat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txttarifrawat = new javax.swing.JTextField();
        btnsimpanrawat = new javax.swing.JButton();
        btnubahrawat = new javax.swing.JButton();
        btnhapusrawat = new javax.swing.JButton();
        btnresetrawat = new javax.swing.JButton();
        pnltblRawat = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblrawat = new javax.swing.JTable();
        pnlalat = new javax.swing.JPanel();
        pnlInputAlat = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtid_alat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtnama_alat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtstok = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txttarif = new javax.swing.JTextField();
        btnsimpanalat = new javax.swing.JButton();
        btnubahalat = new javax.swing.JButton();
        btnhapusalat = new javax.swing.JButton();
        btnresetalat = new javax.swing.JButton();
        pnltblAlat = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblalat = new javax.swing.JTable();
        pnluser = new javax.swing.JPanel();
        pnlInputUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtid_user = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnama_user = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnsimpanuser = new javax.swing.JButton();
        btnubahuser = new javax.swing.JButton();
        btnhapususer = new javax.swing.JButton();
        cbblevel = new javax.swing.JComboBox<>();
        btnresetuser = new javax.swing.JButton();
        pnltblUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbluser = new javax.swing.JTable();
        pnllaporan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbllaporan = new javax.swing.JTable();
        btnlaporancetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnRawat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bed.png"))); // NOI18N
        btnRawat.setText("Rawat ");
        btnRawat.setFocusable(false);
        btnRawat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRawat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRawat.setVerifyInputWhenFocusTarget(false);
        btnRawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRawatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRawat);

        btnAlat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/komponen.png"))); // NOI18N
        btnAlat.setText("Alat ");
        btnAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAlat);

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        btnUser.setText("User ");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUser);

        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporan.png"))); // NOI18N
        btnLaporan.setText("Laporan ");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLaporan);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        pnlUtama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUtama.setLayout(new java.awt.CardLayout());

        pnlrawat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlInputRawat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("ID Rawat");
        pnlInputRawat.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));
        pnlInputRawat.add(txtid_rawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, -1));

        jLabel10.setText("Jenis Rawat");
        pnlInputRawat.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));
        pnlInputRawat.add(txtjenisrawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 110, -1));

        jLabel11.setText("Tarif");
        pnlInputRawat.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));
        pnlInputRawat.add(txttarifrawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 110, -1));

        btnsimpanrawat.setText("Simpan");
        btnsimpanrawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanrawatActionPerformed(evt);
            }
        });
        pnlInputRawat.add(btnsimpanrawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btnubahrawat.setText("Ubah");
        btnubahrawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahrawatActionPerformed(evt);
            }
        });
        pnlInputRawat.add(btnubahrawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        btnhapusrawat.setText("Hapus");
        btnhapusrawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusrawatActionPerformed(evt);
            }
        });
        pnlInputRawat.add(btnhapusrawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        btnresetrawat.setText("Reset Field");
        btnresetrawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetrawatActionPerformed(evt);
            }
        });
        pnlInputRawat.add(btnresetrawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 210, 30));

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        tblrawat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Rawat", "Jenis Rawat", "Tarif"
            }
        ));
        tblrawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblrawatMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblrawat);

        javax.swing.GroupLayout pnltblRawatLayout = new javax.swing.GroupLayout(pnltblRawat);
        pnltblRawat.setLayout(pnltblRawatLayout);
        pnltblRawatLayout.setHorizontalGroup(
            pnltblRawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        pnltblRawatLayout.setVerticalGroup(
            pnltblRawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltblRawatLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlrawatLayout = new javax.swing.GroupLayout(pnlrawat);
        pnlrawat.setLayout(pnlrawatLayout);
        pnlrawatLayout.setHorizontalGroup(
            pnlrawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrawatLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(pnlInputRawat, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnltblRawat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        pnlrawatLayout.setVerticalGroup(
            pnlrawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrawatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlrawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrawatLayout.createSequentialGroup()
                        .addComponent(pnltblRawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrawatLayout.createSequentialGroup()
                        .addComponent(pnlInputRawat, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        pnlUtama.add(pnlrawat, "cardrawat");

        pnlalat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlInputAlat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("ID Alat");
        pnlInputAlat.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));
        pnlInputAlat.add(txtid_alat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 110, -1));

        jLabel15.setText("Nama Alat");
        pnlInputAlat.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));
        pnlInputAlat.add(txtnama_alat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 110, -1));

        jLabel16.setText("Stok");
        pnlInputAlat.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));
        pnlInputAlat.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 110, -1));

        jLabel17.setText("Tarif");
        pnlInputAlat.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));
        pnlInputAlat.add(txttarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 110, -1));

        btnsimpanalat.setText("Simpan");
        btnsimpanalat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanalatActionPerformed(evt);
            }
        });
        pnlInputAlat.add(btnsimpanalat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        btnubahalat.setText("Ubah");
        btnubahalat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahalatActionPerformed(evt);
            }
        });
        pnlInputAlat.add(btnubahalat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        btnhapusalat.setText("Hapus");
        btnhapusalat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusalatActionPerformed(evt);
            }
        });
        pnlInputAlat.add(btnhapusalat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        btnresetalat.setText("Reset Field");
        btnresetalat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetalatActionPerformed(evt);
            }
        });
        pnlInputAlat.add(btnresetalat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, 30));

        jScrollPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane4MouseClicked(evt);
            }
        });

        tblalat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Alat", "Nama Alat", "Stok", "Tarif"
            }
        ));
        tblalat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblalatMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblalat);

        javax.swing.GroupLayout pnltblAlatLayout = new javax.swing.GroupLayout(pnltblAlat);
        pnltblAlat.setLayout(pnltblAlatLayout);
        pnltblAlatLayout.setHorizontalGroup(
            pnltblAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        pnltblAlatLayout.setVerticalGroup(
            pnltblAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltblAlatLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlalatLayout = new javax.swing.GroupLayout(pnlalat);
        pnlalat.setLayout(pnlalatLayout);
        pnlalatLayout.setHorizontalGroup(
            pnlalatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlalatLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(pnlInputAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnltblAlat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        pnlalatLayout.setVerticalGroup(
            pnlalatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlalatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlalatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInputAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnltblAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlUtama.add(pnlalat, "cardalat");

        pnluser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlInputUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID User");
        pnlInputUser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));
        pnlInputUser.add(txtid_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 130, -1));

        jLabel4.setText("Nama User");
        pnlInputUser.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));
        pnlInputUser.add(txtnama_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 130, -1));

        jLabel5.setText("Username");
        pnlInputUser.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));
        pnlInputUser.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 130, -1));

        jLabel6.setText("Password");
        pnlInputUser.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));
        pnlInputUser.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 130, -1));

        jLabel3.setText("Level");
        pnlInputUser.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        btnsimpanuser.setText("Simpan");
        btnsimpanuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanuserActionPerformed(evt);
            }
        });
        pnlInputUser.add(btnsimpanuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 30));

        btnubahuser.setText("Ubah");
        btnubahuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahuserActionPerformed(evt);
            }
        });
        pnlInputUser.add(btnubahuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 30));

        btnhapususer.setText("Hapus");
        btnhapususer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapususerActionPerformed(evt);
            }
        });
        pnlInputUser.add(btnhapususer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, 30));

        cbblevel.setMaximumRowCount(2);
        cbblevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "pegawai" }));
        cbblevel.setToolTipText("");
        cbblevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbblevelActionPerformed(evt);
            }
        });
        pnlInputUser.add(cbblevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 130, -1));

        btnresetuser.setText("Reset Field");
        btnresetuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetuserActionPerformed(evt);
            }
        });
        pnlInputUser.add(btnresetuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, 30));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tbluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID User", "Nama User", "Username", "Password", "Level"
            }
        ));
        tbluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbluserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbluser);

        javax.swing.GroupLayout pnltblUserLayout = new javax.swing.GroupLayout(pnltblUser);
        pnltblUser.setLayout(pnltblUserLayout);
        pnltblUserLayout.setHorizontalGroup(
            pnltblUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );
        pnltblUserLayout.setVerticalGroup(
            pnltblUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltblUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout pnluserLayout = new javax.swing.GroupLayout(pnluser);
        pnluser.setLayout(pnluserLayout);
        pnluserLayout.setHorizontalGroup(
            pnluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnluserLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(pnlInputUser, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnltblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        pnluserLayout.setVerticalGroup(
            pnluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnluserLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnltblUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnluserLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(pnlInputUser, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUtama.add(pnluser, "carduser");

        pnllaporan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbllaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Laporan", "ID Jenis", "Jenis", "Total Harga", "ID Pasien", "Nama Pasien"
            }
        ));
        tbllaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbllaporanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbllaporan);

        btnlaporancetak.setText("Cetak");
        btnlaporancetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporancetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnllaporanLayout = new javax.swing.GroupLayout(pnllaporan);
        pnllaporan.setLayout(pnllaporanLayout);
        pnllaporanLayout.setHorizontalGroup(
            pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllaporanLayout.createSequentialGroup()
                .addGroup(pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnllaporanLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnllaporanLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(btnlaporancetak, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnllaporanLayout.setVerticalGroup(
            pnllaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllaporanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnlaporancetak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlUtama.add(pnllaporan, "cardLaporan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(68, Short.MAX_VALUE)
                    .addComponent(pnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "carduser");
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlatActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardalat");
    }//GEN-LAST:event_btnAlatActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardLaporan");
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new view.formlogin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsimpanuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanuserActionPerformed
        // TODO add your handling code here:
        String iduser = txtid_user.getText();
        String username = txtusername.getText();
        String password = txtpassword.getText();
        String nama = txtnama_user.getText();
        if(cbblevel.getSelectedIndex()==0) {
        String level = cbblevel.getItemAt(0);
        User us = new User(iduser,nama,username,password,level);
        exec.ExecuteUser eUser = new exec.ExecuteUser();
        int hasil = eUser.insertData(us);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        setDataUser();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
        }
        else if (cbblevel.getSelectedIndex()==1){
        String level = cbblevel.getItemAt(1);
        User us = new User(iduser,nama,username,password,level);
        exec.ExecuteUser eUser = new exec.ExecuteUser();
        int hasil = eUser.insertData(us);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        setDataUser();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
        }
    }//GEN-LAST:event_btnsimpanuserActionPerformed

    private void btnubahuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahuserActionPerformed
        // TODO add your handling code here:
        String iduser = txtid_user.getText();
        String username = txtusername.getText();
        String password = txtpassword.getText();
        String nama = txtnama_user.getText();
        if(cbblevel.getSelectedIndex()==0) {
        String level = cbblevel.getItemAt(0);
        User us = new User(iduser,nama,username,password,level);
        exec.ExecuteUser eUser = new exec.ExecuteUser();
        int hasil = eUser.ubahData(us);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        setDataUser();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
        }
        else if (cbblevel.getSelectedIndex()==1){
        String level = cbblevel.getItemAt(1);
        User us = new User(iduser,nama,username,password,level);
        exec.ExecuteUser eUser = new exec.ExecuteUser();
        int hasil = eUser.ubahData(us);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        setDataUser();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
        }
    }//GEN-LAST:event_btnubahuserActionPerformed

    private void btnhapususerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapususerActionPerformed
        // TODO add your handling code here:
        String kode = txtid_user.getText();
        exec.ExecuteUser eUser = new exec.ExecuteUser();
        int hasil = eUser.hapusData(kode);
        if(hasil > 0){
        JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
        setDataUser();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di hapus");
    }//GEN-LAST:event_btnhapususerActionPerformed
    }
    private void tbluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbluserMouseClicked
        // TODO add your handling code here:
        int row = tbluser.getSelectedRow();
        String iduser = tbluser.getValueAt(row, 0).toString();
        String nama = tbluser.getValueAt(row, 1).toString();
        String username = tbluser.getValueAt(row, 2).toString();
        String password = tbluser.getValueAt(row, 3).toString();
        String level = tbluser.getValueAt(row, 4).toString();
        txtid_user.setText(iduser);
        txtnama_user.setText(nama);
        txtusername.setText(username);
        txtpassword.setText(password);
        
    }//GEN-LAST:event_tbluserMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void btnRawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRawatActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardrawat");
    }//GEN-LAST:event_btnRawatActionPerformed

    private void btnsimpanrawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanrawatActionPerformed
        // TODO add your handling code here:
        String idrawat = txtid_rawat.getText();
        String nama = txtjenisrawat.getText();
        String tarif = txttarifrawat.getText();
        int tarif1 = Integer.parseInt(tarif);
        Jenis at = new Jenis(idrawat,nama,tarif1);
        exec.ExecuteJenis eRawat = new exec.ExecuteJenis();
        int hasil = eRawat.insertData(at);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        setDataRawat();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_btnsimpanrawatActionPerformed

    private void btnubahrawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahrawatActionPerformed
        // TODO add your handling code here:
        String idrawat = txtid_rawat.getText();
        String nama = txtjenisrawat.getText();
        String tarif = txttarifrawat.getText();
        int tarif1 = Integer.parseInt(tarif);
        Jenis at = new Jenis(idrawat,nama,tarif1);
        exec.ExecuteJenis eRawat = new exec.ExecuteJenis();
        int hasil = eRawat.ubahData(at);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        setDataRawat();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_btnubahrawatActionPerformed

    private void btnhapusrawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusrawatActionPerformed
        // TODO add your handling code here:
        String kode = txtid_rawat.getText();
        exec.ExecuteJenis eJenis = new exec.ExecuteJenis();
        int hasil = eJenis.hapusData(kode);
        if(hasil > 0){
        JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
        setDataRawat();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di hapus");
    }      
    }//GEN-LAST:event_btnhapusrawatActionPerformed

    private void tblrawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblrawatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblrawatMouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void btnsimpanalatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanalatActionPerformed
        // TODO add your handling code here:
        String idalat = txtid_alat.getText();
        String nama = txtnama_alat.getText();
        String stok = txtstok.getText();
        String tarif = txttarif.getText();
        int stok1 = Integer.parseInt(stok);
        int tarif1 = Integer.parseInt(tarif);
        Alat at = new Alat(idalat, nama,stok1,tarif1);
        exec.ExecuteAlat eBook = new exec.ExecuteAlat();
        int hasil = eBook.insertData(at);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        setDataAlat();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_btnsimpanalatActionPerformed

    private void btnubahalatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahalatActionPerformed
        // TODO add your handling code here:
       String idalat = txtid_alat.getText();
        String nama = txtnama_alat.getText();
        String stok = txtstok.getText();
        String tarif = txttarif.getText();
        int stok1 = Integer.parseInt(stok);
        int tarif1 = Integer.parseInt(tarif);
        Alat at = new Alat(idalat, nama,stok1,tarif1);
        exec.ExecuteAlat eBook = new exec.ExecuteAlat();
        int hasil = eBook.ubahData(at);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        setDataAlat();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_btnubahalatActionPerformed

    private void btnhapusalatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusalatActionPerformed
        // TODO add your handling code here:
        String kode = txtid_alat.getText();
        exec.ExecuteAlat eAlat = new exec.ExecuteAlat();
        int hasil = eAlat.hapusData(kode);
        if(hasil > 0){
        JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
        setDataAlat();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di hapus");
    }//GEN-LAST:event_btnhapusalatActionPerformed
  }
    private void tblalatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblalatMouseClicked
        // TODO add your handling code here:
        int row = tblalat.getSelectedRow();
        String idalat = tblalat.getValueAt(row, 0).toString();
        String nama = tblalat.getValueAt(row, 1).toString();
        String stok = tblalat.getValueAt(row, 2).toString();
        String tarif = tblalat.getValueAt(row, 3).toString();
        txtid_alat.setText(idalat);
        txtnama_alat.setText(nama);
        txtstok.setText(stok);
        txttarif.setText(tarif);
        
    }//GEN-LAST:event_tblalatMouseClicked

    private void jScrollPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4MouseClicked

    private void cbblevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbblevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbblevelActionPerformed

    private void tbllaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbllaporanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbllaporanMouseClicked

    private void btnlaporancetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporancetakActionPerformed
        // TODO add your handling code here:
        int row = tbllaporan.getSelectedRow();
        PrintJob p = getToolkit().getPrintJob(this,"Report",null);
        Graphics g = p.getGraphics();
        g.setFont(new Font("Serif",Font.BOLD,25));
        g.drawString("LAPORAN DATA TRANASKSI PASIEN",100, 50);
        g.setFont(new Font("Serif",Font.PLAIN,12));
        g.drawString("ID Laporan : "+tbllaporan.getValueAt(row, 0),100,100);
        g.drawString("ID Jenis : "+tbllaporan.getValueAt(row, 1),100,130);
        g.drawString("Nama Jenis : "+tbllaporan.getValueAt(row, 2),100,160);
        g.drawString("ID Pasien : "+tbllaporan.getValueAt(row, 4),100,190);
        g.drawString("Nama Pasien : "+tbllaporan.getValueAt(row, 5),100,220);
        g.drawString("Total Harga : "+tbllaporan.getValueAt(row, 3),100,250);
        g.setFont(new Font("Serif",Font.BOLD,12));
        g.setFont(new Font("Serif",Font.PLAIN,12));
        for (int i=0;i<tbllaporan.getModel().getRowCount()-1;i++){
        }
        p.end();
        JOptionPane.showMessageDialog(rootPane,"Data Berhasil diCeak");
        
    }//GEN-LAST:event_btnlaporancetakActionPerformed

    private void btnresetuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetuserActionPerformed
        // TODO add your handling code here:
        txtid_user.setText("");
        txtnama_user.setText("");
        txtusername.setText("");
        txtpassword.setText("");
        cbblevel.setSelectedIndex(0);
        txtid_user.requestFocus();
        
    }//GEN-LAST:event_btnresetuserActionPerformed

    private void btnresetalatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetalatActionPerformed
        // TODO add your handling code here:
        txtid_alat.setText("");
        txtnama_alat.setText("");
        txtstok.setText("");
        txttarif.setText("");
        txtid_alat.requestFocus();
    }//GEN-LAST:event_btnresetalatActionPerformed

    private void btnresetrawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetrawatActionPerformed
        // TODO add your handling code here:
        txtid_rawat.setText("");
        txtjenisrawat.setText("");
        txttarifrawat.setText("");
        txtid_rawat.requestFocus();
    }//GEN-LAST:event_btnresetrawatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormadmin().setVisible(true);
            }
        });
    }
    
     private void setDataUser(){
        ConvertUserToObject cbto = new ConvertUserToObject();
        String[][] dataUser = cbto.getUser();
         tbluser.setModel(new javax.swing.table.DefaultTableModel(
            dataUser,
            new String [] {
                "ID User", "Nama User", "Username", "Password", "Level"
            }
        ));
         jScrollPane1.setViewportView(tbluser);
    }
          private void setDataAlat(){
        ConvertAlatToObject cbto = new ConvertAlatToObject();
        String[][] dataAlat = cbto.getAlat();
         tblalat.setModel(new javax.swing.table.DefaultTableModel(
            dataAlat,
            new String [] {
                "ID Alat", "Nama Alat", "Stok", "Tarif"
            }
        ));
         jScrollPane4.setViewportView(tblalat);
    }
          private void setDataPembayaran(){
        ConvertPembayaranToObject cpto = new ConvertPembayaranToObject();
        String[][] dataPembayaran = cpto.getPembayaran();
         tbllaporan.setModel(new javax.swing.table.DefaultTableModel(
            dataPembayaran,
            new String [] {
                "ID Laporan", "ID Jenis", "Nama Jenis", "Total Harga","ID Pasien","Nama Pasien"
            }
        ));
         jScrollPane2.setViewportView(tbllaporan);
    }
        private void setDataRawat(){
        ConvertJenisToObject cjto = new ConvertJenisToObject();
        String[][] dataJenis = cjto.getJenis();
         tblrawat.setModel(new javax.swing.table.DefaultTableModel(
            dataJenis,
            new String [] {
                "ID Jenis","Nama Jenis", "Tarif"
            }
        ));
         jScrollPane3.setViewportView(tblrawat);
              }
    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlat;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnRawat;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton btnhapusalat;
    private javax.swing.JButton btnhapusrawat;
    private javax.swing.JButton btnhapususer;
    private javax.swing.JButton btnlaporancetak;
    private javax.swing.JButton btnresetalat;
    private javax.swing.JButton btnresetrawat;
    private javax.swing.JButton btnresetuser;
    private javax.swing.JButton btnsimpanalat;
    private javax.swing.JButton btnsimpanrawat;
    private javax.swing.JButton btnsimpanuser;
    private javax.swing.JButton btnubahalat;
    private javax.swing.JButton btnubahrawat;
    private javax.swing.JButton btnubahuser;
    private javax.swing.JComboBox<String> cbblevel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlInputAlat;
    private javax.swing.JPanel pnlInputRawat;
    private javax.swing.JPanel pnlInputUser;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JPanel pnlalat;
    private javax.swing.JPanel pnllaporan;
    private javax.swing.JPanel pnlrawat;
    private javax.swing.JPanel pnltblAlat;
    private javax.swing.JPanel pnltblRawat;
    private javax.swing.JPanel pnltblUser;
    private javax.swing.JPanel pnluser;
    private javax.swing.JTable tblalat;
    private javax.swing.JTable tbllaporan;
    private javax.swing.JTable tblrawat;
    private javax.swing.JTable tbluser;
    private javax.swing.JTextField txtid_alat;
    private javax.swing.JTextField txtid_rawat;
    private javax.swing.JTextField txtid_user;
    private javax.swing.JTextField txtjenisrawat;
    private javax.swing.JTextField txtnama_alat;
    private javax.swing.JTextField txtnama_user;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtstok;
    private javax.swing.JTextField txttarif;
    private javax.swing.JTextField txttarifrawat;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
