/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import com.ConvertAlatToObject;
import com.ConvertUserToObject;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import com.ConvertPasienToObject;
import com.ConvertPembayaranToObject;
import com.Pasien;
import com.Pembayaran;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MuhammadRauf
 */
public class MainFormpegawai extends javax.swing.JFrame {
public Connection conn;
public Statement cn;
    /**
     * Creates new form MainFomadmin
     */
    String dateinap1;
    String datedarurat1;
    String datejalan1;
    
    String datetransaksi;
    
    String datekeluar;
    public MainFormpegawai() {
        initComponents();
        setDataUser();
        setDataPasien();
        setDataRawatInap();
        setDataRawatDarurat();
        setDataRawatJalan();
        setDataAlat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnpasien = new javax.swing.JButton();
        btnRawatinap = new javax.swing.JButton();
        btnrawatdarurat = new javax.swing.JButton();
        btnrawatjalan = new javax.swing.JButton();
        transaksi = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        pnlUtama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlpasien = new javax.swing.JPanel();
        pnlInputUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtid_pasien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnama_pasien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpenyakit = new javax.swing.JTextField();
        btnsimpanpasien = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        pnltblUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpasien = new javax.swing.JTable();
        rawatinap = new javax.swing.JPanel();
        pnlInputinap = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtid_rawatinap = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtid_pasieninap = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnsimpanalat = new javax.swing.JButton();
        dateinap = new com.toedter.calendar.JDateChooser();
        pnltblrawat1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblrawatinap = new javax.swing.JTable();
        pnlrawatdarurat = new javax.swing.JPanel();
        pnlInputRawat = new javax.swing.JPanel();
        btnsimpan1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtid_rawatdarurat = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtid_pasiendarurat = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        datedarurat = new com.toedter.calendar.JDateChooser();
        pnltblRawat = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblrawatdarurat = new javax.swing.JTable();
        pnlrawatjalan = new javax.swing.JPanel();
        pnlInputRawat1 = new javax.swing.JPanel();
        btnsimpan2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtid_rawatjalan = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtid_pasienjalan = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        datejalan = new com.toedter.calendar.JDateChooser();
        pnltblRawat1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblrawatjalan = new javax.swing.JTable();
        pnltransaksi = new javax.swing.JPanel();
        pnlInputRawat2 = new javax.swing.JPanel();
        btnsimpan3 = new javax.swing.JButton();
        btnhitungtransaksi = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtid_rawat2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        datetransaksimasuk = new com.toedter.calendar.JDateChooser();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        datekeluar2 = new com.toedter.calendar.JDateChooser();
        txtid_pasientransaksi = new javax.swing.JTextField();
        txtid_pembayaran2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txttarif = new javax.swing.JTextField();
        txtid_alattransaksi = new javax.swing.JTextField();
        txttanggal = new javax.swing.JTextField();
        pnltblRawat2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblcari = new javax.swing.JTable();
        btnhapus4 = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblalat2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnpasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        btnpasien.setText("Pasien");
        btnpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpasienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnpasien);

        btnRawatinap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bed.png"))); // NOI18N
        btnRawatinap.setText("Rawat Inap");
        btnRawatinap.setFocusable(false);
        btnRawatinap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRawatinap.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRawatinap.setVerifyInputWhenFocusTarget(false);
        btnRawatinap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRawatinapActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRawatinap);

        btnrawatdarurat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ambulance.png"))); // NOI18N
        btnrawatdarurat.setText("Rawat Darurat");
        btnrawatdarurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrawatdaruratActionPerformed(evt);
            }
        });
        jToolBar1.add(btnrawatdarurat);

        btnrawatjalan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        btnrawatjalan.setText("Rawat Jalan");
        btnrawatjalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrawatjalanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnrawatjalan);

        transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaksi.png"))); // NOI18N
        transaksi.setText("Transaksi");
        transaksi.setFocusable(false);
        transaksi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        transaksi.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });
        jToolBar1.add(transaksi);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        logout.setText("Logout");
        logout.setFocusable(false);
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jToolBar1.add(logout);

        pnlUtama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUtama.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELAMAT DATANG PEGAWAI");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlUtama.add(jLabel1, "card2");

        pnlpasien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlInputUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID Pasien");
        pnlInputUser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));
        pnlInputUser.add(txtid_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, -1));

        jLabel4.setText("Nama Pasien");
        pnlInputUser.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));
        pnlInputUser.add(txtnama_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 130, -1));

        jLabel5.setText("Alamat");
        pnlInputUser.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));
        pnlInputUser.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, -1));

        jLabel6.setText("Penyakit");
        pnlInputUser.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));
        pnlInputUser.add(txtpenyakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 130, -1));

        btnsimpanpasien.setText("Simpan");
        btnsimpanpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanpasienActionPerformed(evt);
            }
        });
        pnlInputUser.add(btnsimpanpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        pnlInputUser.add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        pnlInputUser.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblpasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pasien", "Nama Pasien", "Alamat", "Penyakit"
            }
        ));
        tblpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpasien);

        javax.swing.GroupLayout pnltblUserLayout = new javax.swing.GroupLayout(pnltblUser);
        pnltblUser.setLayout(pnltblUserLayout);
        pnltblUserLayout.setHorizontalGroup(
            pnltblUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );
        pnltblUserLayout.setVerticalGroup(
            pnltblUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltblUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout pnlpasienLayout = new javax.swing.GroupLayout(pnlpasien);
        pnlpasien.setLayout(pnlpasienLayout);
        pnlpasienLayout.setHorizontalGroup(
            pnlpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpasienLayout.createSequentialGroup()
                .addComponent(pnlInputUser, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnltblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        pnlpasienLayout.setVerticalGroup(
            pnlpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpasienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInputUser, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnltblUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlUtama.add(pnlpasien, "cardpasien");

        rawatinap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlInputinap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("ID Rawat");
        pnlInputinap.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        txtid_rawatinap.setEditable(false);
        txtid_rawatinap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtid_rawatinap.setText("RWT01");
        pnlInputinap.add(txtid_rawatinap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 110, -1));

        jLabel15.setText("ID Pasien");
        pnlInputinap.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        txtid_pasieninap.setEditable(false);
        txtid_pasieninap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlInputinap.add(txtid_pasieninap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 110, -1));

        jLabel16.setText("Tanggal Masuk");
        pnlInputinap.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        btnsimpanalat.setText("Simpan");
        btnsimpanalat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanalatActionPerformed(evt);
            }
        });
        pnlInputinap.add(btnsimpanalat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 110, 60));

        dateinap.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateinapPropertyChange(evt);
            }
        });
        pnlInputinap.add(dateinap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 110, -1));

        jScrollPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane4MouseClicked(evt);
            }
        });

        tblrawatinap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pembayaran", "ID Rawat", "ID Pasien", "Tanggal Masuk"
            }
        ));
        tblrawatinap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblrawatinapMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblrawatinap);

        javax.swing.GroupLayout pnltblrawat1Layout = new javax.swing.GroupLayout(pnltblrawat1);
        pnltblrawat1.setLayout(pnltblrawat1Layout);
        pnltblrawat1Layout.setHorizontalGroup(
            pnltblrawat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        pnltblrawat1Layout.setVerticalGroup(
            pnltblrawat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltblrawat1Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rawatinapLayout = new javax.swing.GroupLayout(rawatinap);
        rawatinap.setLayout(rawatinapLayout);
        rawatinapLayout.setHorizontalGroup(
            rawatinapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rawatinapLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(pnlInputinap, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnltblrawat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        rawatinapLayout.setVerticalGroup(
            rawatinapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rawatinapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rawatinapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInputinap, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnltblrawat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlUtama.add(rawatinap, "cardinap");

        pnlrawatdarurat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlInputRawat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsimpan1.setText("Simpan");
        btnsimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpan1ActionPerformed(evt);
            }
        });
        pnlInputRawat.add(btnsimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 110, 60));

        jLabel17.setText("ID Rawat");
        pnlInputRawat.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        txtid_rawatdarurat.setEditable(false);
        txtid_rawatdarurat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtid_rawatdarurat.setText("RWT02");
        pnlInputRawat.add(txtid_rawatdarurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, -1));

        jLabel19.setText("ID Pasien");
        pnlInputRawat.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        txtid_pasiendarurat.setEditable(false);
        txtid_pasiendarurat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlInputRawat.add(txtid_pasiendarurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 110, -1));

        jLabel20.setText("Tanggal Masuk");
        pnlInputRawat.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        datedarurat.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datedaruratPropertyChange(evt);
            }
        });
        pnlInputRawat.add(datedarurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 110, -1));

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        tblrawatdarurat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pembayaran", "ID Rawat", "ID Pasien", "Tanggal Masuk"
            }
        ));
        tblrawatdarurat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblrawatdaruratMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblrawatdarurat);
        if (tblrawatdarurat.getColumnModel().getColumnCount() > 0) {
            tblrawatdarurat.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pnltblRawatLayout = new javax.swing.GroupLayout(pnltblRawat);
        pnltblRawat.setLayout(pnltblRawatLayout);
        pnltblRawatLayout.setHorizontalGroup(
            pnltblRawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        pnltblRawatLayout.setVerticalGroup(
            pnltblRawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltblRawatLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlrawatdaruratLayout = new javax.swing.GroupLayout(pnlrawatdarurat);
        pnlrawatdarurat.setLayout(pnlrawatdaruratLayout);
        pnlrawatdaruratLayout.setHorizontalGroup(
            pnlrawatdaruratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrawatdaruratLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(pnlInputRawat, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnltblRawat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        pnlrawatdaruratLayout.setVerticalGroup(
            pnlrawatdaruratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrawatdaruratLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlrawatdaruratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrawatdaruratLayout.createSequentialGroup()
                        .addComponent(pnltblRawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrawatdaruratLayout.createSequentialGroup()
                        .addComponent(pnlInputRawat, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        pnlUtama.add(pnlrawatdarurat, "carddarurat");

        pnlrawatjalan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlInputRawat1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsimpan2.setText("Simpan");
        btnsimpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpan2ActionPerformed(evt);
            }
        });
        pnlInputRawat1.add(btnsimpan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 110, 60));

        jLabel21.setText("ID Rawat");
        pnlInputRawat1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        txtid_rawatjalan.setEditable(false);
        txtid_rawatjalan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtid_rawatjalan.setText("RWT03");
        pnlInputRawat1.add(txtid_rawatjalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, -1));

        jLabel22.setText("ID Pasien");
        pnlInputRawat1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        txtid_pasienjalan.setEditable(false);
        txtid_pasienjalan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlInputRawat1.add(txtid_pasienjalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 110, -1));

        jLabel23.setText("Tanggal Masuk");
        pnlInputRawat1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        datejalan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datejalanPropertyChange(evt);
            }
        });
        pnlInputRawat1.add(datejalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 110, -1));

        jScrollPane5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane5MouseClicked(evt);
            }
        });

        tblrawatjalan.setAutoCreateColumnsFromModel(false);
        tblrawatjalan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pembayaran", "ID Rawat", "ID Pasien", "Tanggal Masuk"
            }
        ));
        tblrawatjalan.setEnabled(false);
        tblrawatjalan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblrawatjalanMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblrawatjalan);

        javax.swing.GroupLayout pnltblRawat1Layout = new javax.swing.GroupLayout(pnltblRawat1);
        pnltblRawat1.setLayout(pnltblRawat1Layout);
        pnltblRawat1Layout.setHorizontalGroup(
            pnltblRawat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        pnltblRawat1Layout.setVerticalGroup(
            pnltblRawat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltblRawat1Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlrawatjalanLayout = new javax.swing.GroupLayout(pnlrawatjalan);
        pnlrawatjalan.setLayout(pnlrawatjalanLayout);
        pnlrawatjalanLayout.setHorizontalGroup(
            pnlrawatjalanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrawatjalanLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(pnlInputRawat1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnltblRawat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        pnlrawatjalanLayout.setVerticalGroup(
            pnlrawatjalanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrawatjalanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlrawatjalanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrawatjalanLayout.createSequentialGroup()
                        .addComponent(pnltblRawat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlrawatjalanLayout.createSequentialGroup()
                        .addComponent(pnlInputRawat1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        pnlUtama.add(pnlrawatjalan, "cardjalan");

        pnltransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlInputRawat2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsimpan3.setText("Simpan");
        btnsimpan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpan3ActionPerformed(evt);
            }
        });
        pnlInputRawat2.add(btnsimpan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        btnhitungtransaksi.setText("Hitung");
        btnhitungtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungtransaksiActionPerformed(evt);
            }
        });
        pnlInputRawat2.add(btnhitungtransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel24.setText("ID Pembayaran");
        pnlInputRawat2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        txtid_rawat2.setEditable(false);
        txtid_rawat2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlInputRawat2.add(txtid_rawat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 110, -1));

        jLabel25.setText("ID Alat");
        pnlInputRawat2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        txttotal.setEditable(false);
        txttotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlInputRawat2.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 120, -1));

        jLabel26.setText("Total Harga");
        pnlInputRawat2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 20));

        datetransaksimasuk.setBackground(new java.awt.Color(255, 255, 255));
        datetransaksimasuk.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datetransaksimasukPropertyChange(evt);
            }
        });
        pnlInputRawat2.add(datetransaksimasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 120, -1));

        jLabel27.setText("Tanggal Masuk");
        pnlInputRawat2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel28.setText("Tanggal Keluar");
        pnlInputRawat2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        datekeluar2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datekeluar2PropertyChange(evt);
            }
        });
        pnlInputRawat2.add(datekeluar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 120, -1));

        txtid_pasientransaksi.setEditable(false);
        txtid_pasientransaksi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlInputRawat2.add(txtid_pasientransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 110, -1));

        txtid_pembayaran2.setEditable(false);
        txtid_pembayaran2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlInputRawat2.add(txtid_pembayaran2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, -1));

        jLabel29.setText("ID Rawat");
        pnlInputRawat2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel30.setText("ID Pasien");
        pnlInputRawat2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        txttarif.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlInputRawat2.add(txttarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 0, 0));

        txtid_alattransaksi.setEditable(false);
        txtid_alattransaksi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlInputRawat2.add(txtid_alattransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 110, -1));
        pnlInputRawat2.add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 0, 0));

        jScrollPane6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane6MouseClicked(evt);
            }
        });

        tblcari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pembayaran", "ID Rawat", "ID Pasien", "Tanggal Masuk"
            }
        ));
        tblcari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcariMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblcari);

        btnhapus4.setText("Cari");
        btnhapus4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapus4ActionPerformed(evt);
            }
        });

        jScrollPane7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane7MouseClicked(evt);
            }
        });

        tblalat2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Alat", "nama_alat", "Stok", "Tarif"
            }
        ));
        tblalat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblalat2MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblalat2);

        javax.swing.GroupLayout pnltblRawat2Layout = new javax.swing.GroupLayout(pnltblRawat2);
        pnltblRawat2.setLayout(pnltblRawat2Layout);
        pnltblRawat2Layout.setHorizontalGroup(
            pnltblRawat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
            .addGroup(pnltblRawat2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnhapus4)
                .addGap(18, 18, 18)
                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnltblRawat2Layout.setVerticalGroup(
            pnltblRawat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltblRawat2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnltblRawat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhapus4)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnltransaksiLayout = new javax.swing.GroupLayout(pnltransaksi);
        pnltransaksi.setLayout(pnltransaksiLayout);
        pnltransaksiLayout.setHorizontalGroup(
            pnltransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltransaksiLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(pnlInputRawat2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnltblRawat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        pnltransaksiLayout.setVerticalGroup(
            pnltransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltransaksiLayout.createSequentialGroup()
                .addComponent(pnltblRawat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltransaksiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlInputRawat2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pnlUtama.add(pnltransaksi, "cardtransaksi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(67, Short.MAX_VALUE)
                    .addComponent(pnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpasienActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardpasien");
    }//GEN-LAST:event_btnpasienActionPerformed

    private void btnrawatdaruratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrawatdaruratActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "carddarurat");
    }//GEN-LAST:event_btnrawatdaruratActionPerformed

    private void btnrawatjalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrawatjalanActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardjalan");
    }//GEN-LAST:event_btnrawatjalanActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new view.formlogin().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void btnsimpanpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanpasienActionPerformed
        // TODO add your handling code here:
        String idpasien = txtid_pasien.getText();
        String nama = txtnama_pasien.getText();
        String alamat = txtalamat.getText();
        String penyakit = txtpenyakit.getText();
        Pasien ps = new Pasien(idpasien, nama,alamat,penyakit);
        exec.ExecutePasien ePasien = new exec.ExecutePasien();
        int hasil = ePasien.insertData(ps);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        setDataPasien();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
        txtid_pasienjalan.setText(idpasien);
        txtid_pasiendarurat.setText(idpasien);
        txtid_pasieninap.setText(idpasien);
        txtid_pasien.setText("");
        txtnama_pasien.setText("");
        txtalamat.setText("");
        txtpenyakit.setText("");
    }//GEN-LAST:event_btnsimpanpasienActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        String idpasien = txtid_pasien.getText();
        String nama = txtnama_pasien.getText();
        String alamat = txtalamat.getText();
        String penyakit = txtpenyakit.getText();
        Pasien ps = new Pasien(idpasien, nama,alamat,penyakit);
        exec.ExecutePasien ePasien = new exec.ExecutePasien();
        int hasil = ePasien.ubahData(ps);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        setDataPasien();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
        txtid_pasienjalan.setText(idpasien);
        txtid_pasiendarurat.setText(idpasien);
        txtid_pasieninap.setText(idpasien);
        txtid_pasien.setText("");
        txtnama_pasien.setText("");
        txtalamat.setText("");
        txtpenyakit.setText("");
        
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        String kode = txtid_pasien.getText();
        exec.ExecutePasien ePasien = new exec.ExecutePasien();
        int hasil = ePasien.hapusData(kode);
        if(hasil > 0){
        JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
        setDataPasien();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di hapus");
    }      
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tblpasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpasienMouseClicked
        // TODO add your handling code here:
        int row = tblpasien.getSelectedRow();
        String iduser = tblpasien.getValueAt(row, 0).toString();
        String nama = tblpasien.getValueAt(row, 1).toString();
        String username = tblpasien.getValueAt(row, 2).toString();
        String password = tblpasien.getValueAt(row, 3).toString();
        txtid_pasien.setText(iduser);
        txtnama_pasien.setText(nama);
        txtalamat.setText(username);
        txtpenyakit.setText(password);      
    }//GEN-LAST:event_tblpasienMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void btnRawatinapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRawatinapActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardinap");
    }//GEN-LAST:event_btnRawatinapActionPerformed

    private void btnsimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpan1ActionPerformed
        // TODO add your handling code here:
        String rawat = txtid_rawatdarurat.getText();
        String pasien = txtid_pasiendarurat.getText();
        String masuk = datedarurat1;
        Pembayaran py = new Pembayaran(rawat,masuk,pasien);
        exec.ExecutePembayaran eTrass = new exec.ExecutePembayaran();
        int hasil = eTrass.insertData(py);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        setDataRawatInap();
        setDataRawatDarurat();
        setDataRawatJalan();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
        txtid_rawatdarurat.setText("");
        txtid_pasiendarurat.setText("");
        datedarurat.setDate(null);
        txtid_rawatinap.setText("");
        txtid_pasieninap.setText("");
        dateinap.setDate(null);
        txtid_rawatjalan.setText("");
        txtid_pasienjalan.setText("");
        datejalan.setDate(null);
    }//GEN-LAST:event_btnsimpan1ActionPerformed

    private void tblrawatdaruratMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblrawatdaruratMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblrawatdaruratMouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void btnsimpanalatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanalatActionPerformed
        // TODO add your handling code here:
        String rawat = txtid_rawatinap.getText();
        String pasien = txtid_pasieninap.getText();
        String masuk = dateinap1;
        Pembayaran py = new Pembayaran(rawat,masuk,pasien);
        exec.ExecutePembayaran eTrass = new exec.ExecutePembayaran();
        int hasil = eTrass.insertData(py);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        setDataRawatInap();
        setDataRawatDarurat();
        setDataRawatJalan();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
        txtid_rawatdarurat.setText("");
        txtid_pasiendarurat.setText("");
        datedarurat.setDate(null);
        txtid_rawatinap.setText("");
        txtid_pasieninap.setText("");
        dateinap.setDate(null);
        txtid_rawatjalan.setText("");
        txtid_pasienjalan.setText("");
        datejalan.setDate(null);
    }//GEN-LAST:event_btnsimpanalatActionPerformed
  
    private void tblrawatinapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblrawatinapMouseClicked
        // TODO add your handling code here:      
    }//GEN-LAST:event_tblrawatinapMouseClicked

    private void jScrollPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4MouseClicked

    private void tblrawatjalanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblrawatjalanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblrawatjalanMouseClicked

    private void jScrollPane5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane5MouseClicked

    private void btnsimpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpan2ActionPerformed
        // TODO add your handling code here:
        String rawat = txtid_rawatjalan.getText();
        String pasien = txtid_pasienjalan.getText();
        String masuk = datejalan1;
        Pembayaran py = new Pembayaran(rawat,masuk,pasien);
        exec.ExecutePembayaran eTrass = new exec.ExecutePembayaran();
        int hasil = eTrass.insertData(py);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        setDataRawatInap();
        setDataRawatDarurat();
        setDataRawatJalan();
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
        txtid_rawatdarurat.setText("");
        txtid_pasiendarurat.setText("");
        datedarurat.setDate(null);
        txtid_rawatinap.setText("");
        txtid_pasieninap.setText("");
        dateinap.setDate(null);
        txtid_rawatjalan.setText("");
        txtid_pasienjalan.setText("");
        datejalan.setDate(null);
    }//GEN-LAST:event_btnsimpan2ActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardtransaksi");
    }//GEN-LAST:event_transaksiActionPerformed

    private void dateinapPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateinapPropertyChange
        // TODO add your handling code here:
      if (dateinap.getDate() != null) {
      SimpleDateFormat FormatTanggal = new SimpleDateFormat("dd MMMM yyyy");
      dateinap1 = FormatTanggal.format(dateinap.getDate());
        }
    }//GEN-LAST:event_dateinapPropertyChange

    private void datedaruratPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datedaruratPropertyChange
        // TODO add your handling code here:
      if (datedarurat.getDate() != null) {
      SimpleDateFormat FormatTanggal = new SimpleDateFormat("dd MMMM yyyy");
      datedarurat1 = FormatTanggal.format(datedarurat.getDate());
        }
    }//GEN-LAST:event_datedaruratPropertyChange

    private void datejalanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datejalanPropertyChange
        // TODO add your handling code here:
      if (datejalan.getDate() != null) {
      SimpleDateFormat FormatTanggal = new SimpleDateFormat("dd MMMM yyyy");
      datejalan1 = FormatTanggal.format(datejalan.getDate());
        }
    }//GEN-LAST:event_datejalanPropertyChange

    private void btnsimpan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpan3ActionPerformed
        // TODO add your handling code here:
        String id = txtid_pembayaran2.getText();
        String alat = txtid_alattransaksi.getText();
        String keluar = txttanggal.getText();
        String total = txttotal.getText();
        int total1 = Integer.parseInt(total);
        int id2 = Integer.parseInt(id);
        Pembayaran py = new Pembayaran(id2,keluar,total1,alat);
        exec.ExecutePembayaran eTrass = new exec.ExecutePembayaran();
        int hasil = eTrass.ubahData(py);
        if(hasil >0){
        JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
        }
        else{
        JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
        
        PrintJob p = getToolkit().getPrintJob(this,"Report",null);
        Graphics g = p.getGraphics();
        g.setFont(new Font("Serif",Font.BOLD,25));
        g.drawString("STRUK TRANSAKSI PASIEN",100, 50);
        g.setFont(new Font("Serif",Font.PLAIN,12));
        g.drawString("ID Pembayaran : "+txtid_pembayaran2,100,100);
        g.drawString("ID Rawat : "+txtid_rawat2,100,130);
        g.drawString("ID Pasien : "+txtid_pasientransaksi,100,160);
        g.drawString("ID Alat: "+txtid_alattransaksi,100,190);
        g.drawString("Tanggal Masuk : "+datetransaksimasuk,100,220);
        g.drawString("Tanggal Keluar : "+datekeluar2,100,250);
        g.drawString("Total Harga : "+txttotal,100,250);
        g.setFont(new Font("Serif",Font.BOLD,12));
        g.setFont(new Font("Serif",Font.PLAIN,12));
        JOptionPane.showMessageDialog(rootPane,"Data Berhasil diCeak");
        
    }//GEN-LAST:event_btnsimpan3ActionPerformed

    private void btnhitungtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungtransaksiActionPerformed
        // TODO add your handling code here:
    try {
    DateFormat format = new SimpleDateFormat("dd MMMM yyyy");
    Date tanggalpinjam = format.parse(datetransaksi);
    Date tanggalkembali = format.parse(datekeluar);
    long tanggalpinjam1 = tanggalpinjam.getTime();
    long tanggalkembali1 = tanggalkembali.getTime();
    long diff = tanggalkembali1 - tanggalpinjam1;
    long lama = diff / (24 * 60 * 60 * 1000);
    long hasil,total;
    long tarif = Integer.parseInt(txttarif.getText());
    
    if (txtid_rawat2.getText().equals("RWT01")){
        hasil = lama * 200000;
        total = hasil + tarif;
        String a = String.valueOf(total);
        txttotal.setText(a);
    }
   else if (txtid_rawat2.getText().equals("RWT02")){
        hasil = lama * 100000;
        total = hasil + tarif;
        String a = String.valueOf(total);
        txttotal.setText(a);
    }
   else if (txtid_rawat2.getText().equals("RWT03")){
        hasil = lama * 90000;
        total = hasil + tarif;
        String a = String.valueOf(total);
        txttotal.setText(a);
    }
    else{
    txttotal.setText("0");   
    }
} catch (Exception e) {
    System.out.println("" + e.getMessage());
}
    String tampilan = "dd MMMM yyyy";
        SimpleDateFormat format = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(format.format(datekeluar2.getDate()));
        txttanggal.setText(tanggal);
    }//GEN-LAST:event_btnhitungtransaksiActionPerformed

    private void datetransaksimasukPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datetransaksimasukPropertyChange
        // TODO add your handling code here:
       if (datetransaksimasuk.getDate() != null) {
      SimpleDateFormat FormatTanggal = new SimpleDateFormat("dd MMMM yyyy");
      datetransaksi = FormatTanggal.format(datetransaksimasuk.getDate());
        } 
    }//GEN-LAST:event_datetransaksimasukPropertyChange

    private void tblcariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcariMouseClicked
        // TODO add your handling code here:
        int row = tblcari.getSelectedRow();
        String transaksi = tblcari.getValueAt(row, 0).toString();
        if(evt.getClickCount()==1){
            datetransaksimasuk.setDate(getTanggalFromTable(tblcari,2));
        }
        String iduser = tblcari.getValueAt(row, 0).toString();
        String nama = tblcari.getValueAt(row, 1).toString();
        String username = tblcari.getValueAt(row, 3).toString();
        txtid_pembayaran2.setText(iduser);
        txtid_rawat2.setText(nama);
        txtid_pasientransaksi.setText(username);
    }//GEN-LAST:event_tblcariMouseClicked

    private void jScrollPane6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane6MouseClicked

    private void btnhapus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapus4ActionPerformed
        // TODO add your handling code here:
    DefaultTableModel tabelnyo = new DefaultTableModel();
    tabelnyo.addColumn("ID Pembayaran");
    tabelnyo.addColumn("ID Rawat");
    tabelnyo.addColumn("Tanggal Masuk");
    tabelnyo.addColumn("ID Pasein");
    try{ 
    koneksi();
    String sql = "Select id_pembayaran,id_jenis,tgl_masuk,id_pasien from pembayaran where id_pasien like '%" +
    txtcari.getText() + "%'";
    ResultSet rs = cn.executeQuery(sql);
    while (rs.next()) {
    tabelnyo.addRow(new Object[]{
    rs.getString(1),
    rs.getString(2),
    rs.getString(3),
    rs.getString(4)
    });
    }
    tblcari.setModel(tabelnyo);
}catch (Exception e){
 
}
    }//GEN-LAST:event_btnhapus4ActionPerformed

    private void datekeluar2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datekeluar2PropertyChange
        // TODO add your handling code here:
      if (datekeluar2.getDate()!= null) {
      SimpleDateFormat FormatTanggal = new SimpleDateFormat("dd MMMM yyyy");
      datekeluar = FormatTanggal.format(datekeluar2.getDate());
        } 
    }//GEN-LAST:event_datekeluar2PropertyChange

    private void tblalat2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblalat2MouseClicked
        // TODO add your handling code here:
        int row = tblalat2.getSelectedRow();
        String iduser = tblalat2.getValueAt(row, 0).toString();
        String nama = tblalat2.getValueAt(row, 3).toString();
        txtid_alattransaksi.setText(iduser);
        txttarif.setText(nama);
    }//GEN-LAST:event_tblalat2MouseClicked

    private void jScrollPane7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }
     private void setDataUser(){
        ConvertUserToObject cbto = new ConvertUserToObject();
        String[][] dataUser = cbto.getUser();
         tblpasien.setModel(new javax.swing.table.DefaultTableModel(
            dataUser,
            new String [] {
                "ID User", "Nama User", "Username", "Password", "Level"
            }
        ));
         jScrollPane1.setViewportView(tblpasien);
    }
        private void setDataPasien(){
        ConvertPasienToObject cpto = new ConvertPasienToObject();
        String[][] dataPasien = cpto.getPasien();
         tblpasien.setModel(new javax.swing.table.DefaultTableModel(
            dataPasien,
            new String [] {
                "ID Pasien", "Nama Pasien", "Alamat", "Diagnosis Penyakit"
            }
        ));
         jScrollPane1.setViewportView(tblpasien);
    }
        
        private void setDataRawatInap(){
        ConvertPembayaranToObject cpto = new ConvertPembayaranToObject();
        String[][] datapembayaraninap = cpto.getPembayaranInap();
         tblrawatinap.setModel(new javax.swing.table.DefaultTableModel(
            datapembayaraninap,
            new String [] {
                "ID Pembayaran", "ID Rawat", "ID Pasien", "Tanggal Masuk"
            }
        ));
         jScrollPane4.setViewportView(tblrawatinap);
    }
        private void setDataRawatDarurat(){
        ConvertPembayaranToObject cpto = new ConvertPembayaranToObject();
        String[][] datapembayarandarurat = cpto.getPembayaranDarurat();
         tblrawatdarurat.setModel(new javax.swing.table.DefaultTableModel(
            datapembayarandarurat,
            new String [] {
                "ID Pembayaran", "ID Rawat", "ID Pasien", "Tanggal Masuk"
            }
        ));
         jScrollPane3.setViewportView(tblrawatdarurat);
    }
        private void setDataRawatJalan(){
        ConvertPembayaranToObject cpto = new ConvertPembayaranToObject();
        String[][] datapembayaranjalan = cpto.getPembayaranJalan();
         tblrawatjalan.setModel(new javax.swing.table.DefaultTableModel(
            datapembayaranjalan,
            new String [] {
                "ID Pembayaran", "ID Rawat", "ID Pasien", "Tanggal Masuk"
            }
        ));
         jScrollPane5.setViewportView(tblrawatjalan);
    }
         
    public void koneksi(){
    try{
    Class.forName("com.mysql.jdbc.Driver");
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/biling","root","");
    cn = conn.createStatement();
    }catch (Exception e){
    JOptionPane.showMessageDialog(this,"koneksi gagal..",
    "Error",JOptionPane.ERROR_MESSAGE);
    System.out.println(e.getMessage());
        }
    }
   
    public static Date getTanggalFromTable(JTable table, int kolom){
    JTable tabel = table;
    String str_tgl = String.valueOf(tabel.getValueAt(tabel.getSelectedRow(), kolom));
    Date tanggal = null;
        try {
            tanggal = new SimpleDateFormat("dd MMMM yyyy").parse(str_tgl);
        } catch (ParseException ex) {
            Logger.getLogger(MainFormpegawai.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tanggal;

    } 
     private void setDataAlat(){
        ConvertAlatToObject cbto = new ConvertAlatToObject();
        String[][] dataAlat = cbto.getAlat();
         tblalat2.setModel(new javax.swing.table.DefaultTableModel(
            dataAlat,
            new String [] {
                "ID Alat", "Nama Alat", "Stok", "Tarif"
            }
        ));
         jScrollPane7.setViewportView(tblalat2);
    }
    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRawatinap;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnhapus4;
    private javax.swing.JButton btnhitungtransaksi;
    private javax.swing.JButton btnpasien;
    private javax.swing.JButton btnrawatdarurat;
    private javax.swing.JButton btnrawatjalan;
    private javax.swing.JButton btnsimpan1;
    private javax.swing.JButton btnsimpan2;
    private javax.swing.JButton btnsimpan3;
    private javax.swing.JButton btnsimpanalat;
    private javax.swing.JButton btnsimpanpasien;
    private javax.swing.JButton btnubah;
    private com.toedter.calendar.JDateChooser datedarurat;
    private com.toedter.calendar.JDateChooser dateinap;
    private com.toedter.calendar.JDateChooser datejalan;
    private com.toedter.calendar.JDateChooser datekeluar2;
    private com.toedter.calendar.JDateChooser datetransaksimasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton logout;
    private javax.swing.JPanel pnlInputRawat;
    private javax.swing.JPanel pnlInputRawat1;
    private javax.swing.JPanel pnlInputRawat2;
    private javax.swing.JPanel pnlInputUser;
    private javax.swing.JPanel pnlInputinap;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JPanel pnlpasien;
    private javax.swing.JPanel pnlrawatdarurat;
    private javax.swing.JPanel pnlrawatjalan;
    private javax.swing.JPanel pnltblRawat;
    private javax.swing.JPanel pnltblRawat1;
    private javax.swing.JPanel pnltblRawat2;
    private javax.swing.JPanel pnltblUser;
    private javax.swing.JPanel pnltblrawat1;
    private javax.swing.JPanel pnltransaksi;
    private javax.swing.JPanel rawatinap;
    private javax.swing.JTable tblalat2;
    private javax.swing.JTable tblcari;
    private javax.swing.JTable tblpasien;
    private javax.swing.JTable tblrawatdarurat;
    private javax.swing.JTable tblrawatinap;
    private javax.swing.JTable tblrawatjalan;
    private javax.swing.JButton transaksi;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid_alattransaksi;
    private javax.swing.JTextField txtid_pasien;
    private javax.swing.JTextField txtid_pasiendarurat;
    private javax.swing.JTextField txtid_pasieninap;
    private javax.swing.JTextField txtid_pasienjalan;
    private javax.swing.JTextField txtid_pasientransaksi;
    private javax.swing.JTextField txtid_pembayaran2;
    private javax.swing.JTextField txtid_rawat2;
    private javax.swing.JTextField txtid_rawatdarurat;
    private javax.swing.JTextField txtid_rawatinap;
    private javax.swing.JTextField txtid_rawatjalan;
    private javax.swing.JTextField txtnama_pasien;
    private javax.swing.JTextField txtpenyakit;
    private javax.swing.JTextField txttanggal;
    private javax.swing.JTextField txttarif;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
